### ISSUE TITLE
Redmine 3.3.3: Error 500

### ISSUE THREAD

**Issue by fjudith** [dr-itz/redmine_workflow_enhancements#17]
Hello, 

Welcome page displays an Error 500 using Redmine 3.3.3

**production.log**

```
...
plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action
_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action
_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action
_view_rendering.rb:53:in `render_with_workflow_enhancements'
  app/views/welcome/index.html.erb:14:in `_1d3e1b232314eba66d7c54a44fbe0d97'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I can get the welcome page once putting comment on line 53

` result = render_with_workflow_enhancements(*args, &block)`

But latest news does not display.

**Comment by dr-itz** [comment]
Please post the full error message. With this I can't do anything...
Also, what environment? Platform, Ruby version, etc.?

**Comment by fjudith** [comment]
I recently moved to redmine 3.3.4
Error basically happen once i connect to redmine (i.e login page)

### plugin install

```
pushd plugins/
git clone -b master --single-branch https://github.com/dr-itz/redmine_workflow_enhancements
```

### environment
```
Environment:
  Redmine version                3.3.4.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

### logs

```
Started GET "/" for 127.0.0.1 at 2017-07-09 13:44:43 +0000
Processing by WelcomeController#index as HTML
  Current user: fjudith (id=5)
  Rendered welcome/index.html.erb within layouts/base (81.6ms)
Completed 500 Internal Server Error in 195ms (ActiveRecord: 14.4ms)

SystemStackError (stack level too deep):
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:661
```

**Comment by stekaa** [comment]
I just tried to run this plugin in redmine 3.4.6 --> Error 500

log:
```
Started GET "/" for 127.0.0.1 at 2018-10-02 08:27:50 +0200
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (2.4ms)
Completed 500 Internal Server Error in 94ms (ActiveRecord: 3.7ms)

SystemStackError (stack level too deep):
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
... repeat > 2000 times ...
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___489822054319477847_47279067413980'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Environment:
```
  Redmine version                3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

```

It turned out that this plugin is not compatible with another plugin. In my case the other plugin is redmine_issues_tree. After uninstalling the other plugin this one works.

**Comment by zealings** [comment]
I got a 500 error when used with redmine_dashboard.
After removing this, it works normally.

https://github.com/jgraichen/redmine_dashboard
