### ISSUE TITLE
Error 500 - Redmine 3.3.3

### ISSUE THREAD

**Issue by publicvirtualvoid** [dr-itz/redmine_workflow_enhancements#18]
Similar to #17, but the error is different so I created a new issue.

From production.log:
```Started GET "/workflows/edit?utf8=%E2%9C%93&role_id%5B%5D=3&tracker_id%5B%5D=1&used_statuses_only=0&used_statuses_only=1" for 172.17.0.2 at 2017-07-05 23:59:45 +0000
Processing by WorkflowsController#edit as HTML
  Parameters: {"utf8"=>"✓", "role_id"=>["3"], "tracker_id"=>["1"], "used_statuses_only"=>"1"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.8ms)

NameError (uninitialized constant Tracker::TrackerStatus):
  plugins/redmine_workflow_enhancements-master/lib/workflow_enhancements/patches/tracker_patch.rb:18:in 'issue_statuses_with_workflow_enhancements'
  app/controllers/workflows_controller.rb:140:in 'map'
  app/controllers/workflows_controller.rb:140:in 'find_statuses'
  app/controllers/workflows_controller.rb:114:in 'find_trackers_roles_and_statuses_for_edit'
  app/controllers/workflows_controller.rb:30:in 'edit'
  lib/redmine/sudo_mode.rb:63:in 'sudo_mode'```

**Comment by dr-itz** [comment]
Please fix the name of the directory, then retry:

~~~~
mv plugins/redmine_workflow_enhancements-master plugins/redmine_workflow_enhancements
~~~~

**Comment by publicvirtualvoid** [comment]
You're right, silly me!
