### ISSUE TITLE
Support for 4.0

### ISSUE THREAD

**Issue by TrumanRu** [dr-itz/redmine_workflow_enhancements#23]
Very nice plugin I used for all my projects in Redmine 3.3 & 3.4 for more than 3 years.

Now my first Redmine 4.0 installation on:
```
Environment:
  Redmine version                4.0.4.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.3
```
**root@tbd8:/opt/redmine/plugins# rake redmine:plugins:migrate RAILS_ENV=production**
```
(in /opt/redmine)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateTrackerStatuses < ActiveRecord::Migration[4.2]/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:528:in `inherited'
/opt/redmine/plugins/redmine_workflow_enhancements/db/migrate/001_create_tracker_statuses.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:986:in `load_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:982:in `migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1350:in `use_transaction?'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1342:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:504:in `up'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:491:in `block in migrate'
/opt/redmine/lib/redmine/plugin.rb:490:in `each'
/opt/redmine/lib/redmine/plugin.rb:490:in `migrate'
/opt/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateTrackerStatuses < ActiveRecord::Migration[4.2]/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:528:in `inherited'
/opt/redmine/plugins/redmine_workflow_enhancements/db/migrate/001_create_tracker_statuses.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:986:in `load_migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:982:in `migration'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1350:in `use_transaction?'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1342:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:504:in `up'
/var/lib/gems/2.3.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:536:in `migrate_plugin'
/opt/redmine/lib/redmine/plugin.rb:477:in `migrate'
/opt/redmine/lib/redmine/plugin.rb:491:in `block in migrate'
/opt/redmine/lib/redmine/plugin.rb:490:in `each'
/opt/redmine/lib/redmine/plugin.rb:490:in `migrate'
/opt/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by hboetes** [comment]
Yes, please upgrade this plugin to support 4.0, it's been out for over 9 month now.

**Comment by senguttuvang** [comment]
@RailsDevs - Please help us to resolve the issue.

**Comment by albrechtd** [comment]
+1 – a fix for 4.0 will he highly appreciated!
